#!/usr/bin/env bash
TRY_LOOP=10

echo "Running pipe-airflow $1"

case $1 in
  webserver)
    exec airflow webserver
    ;;
  scheduler)
    ./dags
    exec airflow scheduler
    ;;
  waitdb)
    ./waitdb
    ;;
  initialize)
    ./initialize
    ;;
  *)
    echo "Invalid arguments $@"
esac
