#!/usr/bin/env bash
TRY_LOOP=10

echo "Running airflow $1"

# wait for DB
echo "Waiting until database is ready at ${CLOUDSQL_SERVICE_HOST}:${CLOUDSQL_SERVICE_PORT}"
i=0
while ! nc -v -w 5 $CLOUDSQL_SERVICE_HOST $CLOUDSQL_SERVICE_PORT < /dev/null; do
  i=`expr $i + 1`
  if [ $i -ge $TRY_LOOP ]; then
    echo "$(date) - ${CLOUDSQL_SERVICE_HOST}:${CLOUDSQL_SERVICE_PORT} still not reachable, giving up"
    exit 1
  fi
  echo "$(date) - waiting for ${CLOUDSQL_SERVICE_HOST}:${CLOUDSQL_SERVICE_PORT}... $i/$TRY_LOOP"
  sleep 5
done
echo "Database is ready at ${CLOUDSQL_SERVICE_HOST}:${CLOUDSQL_SERVICE_PORT}"
